package com.muhasib.soft.ui.list

import com.muhasib.soft.R

enum class ListType(val titleRes: Int, val cols: List<Int>) {
    SALES(R.string.sales, listOf(R.string.number, R.string.date, R.string.name, R.string.amount)),
    PURCHASES(R.string.purchases, listOf(R.string.number, R.string.date, R.string.name, R.string.amount)),
    RECEIPTS(R.string.receipt_payment, listOf(R.string.voucher_no, R.string.date, R.string.total_sum, R.string.description, R.string.doc_type)),
    QUOTES(R.string.quote_invoice, listOf(R.string.number, R.string.date, R.string.name, R.string.amount)),
    PURCHASE_ORDERS(R.string.purchase_order, listOf(R.string.number, R.string.date, R.string.name, R.string.amount)),
    WAREHOUSES(R.string.warehouses_title, listOf(R.string.warehouse_name, R.string.phone, R.string.address)),
    CASHBOXES(R.string.cashboxes_title, listOf(R.string.name, R.string.phone, R.string.address, R.string.tax_number)),
    ACCOUNTS(R.string.chart_of_accounts, listOf(R.string.account_name, R.string.account_type, R.string.accounts_count)),
    ITEMS(R.string.items_list, listOf(R.string.item_name, R.string.group, R.string.opening_qty, R.string.unit_cost)),
    PRICES(R.string.sale_prices, listOf(R.string.item_name, R.string.sale_price, R.string.cost, R.string.price_date)),
    ITEM_UNITS(R.string.item_units, listOf(R.string.item_name, R.string.unit, R.string.pack, R.string.base_unit)),
    CURRENCIES(R.string.currencies, listOf(R.string.currency, R.string.category, R.string.symbol, R.string.accounts_count)),
    RATES(R.string.exchange_rate, listOf(R.string.currency, R.string.exchange_rate, R.string.from_date, R.string.to_date)),
    CEILINGS(R.string.ceil_debit, listOf(R.string.account, R.string.currency, R.string.ceil_debit, R.string.ceil_credit)),
    GROUPS(R.string.item_groups, listOf(R.string.group_name, R.string.items_count)),
    UNITS(R.string.units_of_measure, listOf(R.string.unit_name, R.string.abbrev)),
    CLASSES(R.string.classifications, listOf(R.string.classification, R.string.accounts_count)),
    USERS(R.string.users_permissions, listOf(R.string.name, R.string.cashbox, R.string.warehouse)),
    REMINDERS(R.string.reminders, listOf(R.string.name, R.string.date, R.string.time, R.string.note)),
    STATEMENT(R.string.statement, listOf(R.string.date, R.string.description, R.string.debit, R.string.credit_side, R.string.balance)),
    JOURNAL_LIST(R.string.daily_journals, listOf(R.string.date, R.string.number, R.string.account, R.string.debit, R.string.credit_side)),
    REP_MOVEMENT(R.string.item_movement, listOf(R.string.item, R.string.description, R.string.warehouse, R.string.qty, R.string.price, R.string.total)),
    REP_REMAINING(R.string.remaining_stock, listOf(R.string.item, R.string.warehouse, R.string.qty, R.string.sale_price, R.string.cost, R.string.total)),
    REP_BALANCES(R.string.account_balances, listOf(R.string.account, R.string.balance)),
    REP_TRIAL(R.string.trial_balance, listOf(R.string.account, R.string.debit, R.string.credit_side)),
    REP_INCOME(R.string.income_statement, listOf(R.string.account, R.string.amount)),
    REP_FINANCIAL(R.string.financial_position, listOf(R.string.assets, R.string.liabilities_equity)),
    REP_OTHERS(R.string.other_reports, listOf(R.string.other_reports)),
    REP_DAILY_OPS(R.string.daily_ops, listOf(R.string.date, R.string.number, R.string.movement_type, R.string.amount)),
    REP_DAILY_JOURNALS(R.string.daily_journals, listOf(R.string.date, R.string.number, R.string.account, R.string.debit, R.string.credit_side)),
    REP_CASHBOX_MOVE(R.string.cashbox_movement, listOf(R.string.date, R.string.number, R.string.account, R.string.amount)),
    REP_ACCOUNTS_MOVE(R.string.accounts_movement, listOf(R.string.date, R.string.account, R.string.debit, R.string.credit_side)),
    REP_CLASS_TOTALS(R.string.class_totals, listOf(R.string.classification, R.string.amount)),
    REP_CURRENCY_DIFF(R.string.currency_diff, listOf(R.string.currency, R.string.from_date, R.string.exchange_rate)),
    REP_WORKING(R.string.working_capital, listOf(R.string.account, R.string.amount)),
    REP_CUSTOMER_PROFIT(R.string.customer_profit, listOf(R.string.name, R.string.profit)),
    REP_SALES_BY_ITEM(R.string.sales_by_item, listOf(R.string.item, R.string.qty, R.string.total)),
    REP_PURCHASES_BY_ITEM(R.string.purchases_by_item, listOf(R.string.item, R.string.qty, R.string.total)),
    REP_ITEM_PROFITS(R.string.item_profits, listOf(R.string.item, R.string.profit, R.string.total)),
    REP_MOVEMENT_DETAILS(R.string.item_movement_details, listOf(R.string.date, R.string.item, R.string.movement_type, R.string.qty, R.string.total))
}
